"""initial schema

Revision ID: e0e7b7e96625
Revises: 
Create Date: 2026-08-30 02:45:57.123642
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariffs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sites_limit', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Enum('month', 'month3', 'month6', 'month12', 'forever', name='tariff_duration_enum'), nullable=False),
    sa.Column('price_ton', sa.Numeric(precision=20, scale=9), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('kind', sa.Enum('base', 'pro', 'custom_code', name='tariff_kind_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ton_proof_payloads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payload', sa.String(length=128), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ton_proof_payloads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ton_proof_payloads_payload'), ['payload'], unique=True)
        batch_op.create_index(batch_op.f('ix_ton_proof_payloads_telegram_id'), ['telegram_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('wallet_address', sa.String(length=128), nullable=True),
    sa.Column('language', sa.Enum('ru', 'en', name='language_enum'), nullable=False),
    sa.Column('theme', sa.Enum('light', 'dark', name='theme_enum'), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_telegram_id'), ['telegram_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_wallet_address'), ['wallet_address'], unique=False)

    op.create_table('admin_actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('admin_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.Enum('grant_access', 'revoke_access', 'change_price', 'create_tariff', 'delete_tariff', name='admin_action_enum'), nullable=False),
    sa.Column('target_user_id', sa.Uuid(), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_actions_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_actions_target_user_id'), ['target_user_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tx_hash', sa.String(length=128), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=9), nullable=False),
    sa.Column('purpose', sa.Enum('subscription', 'custom_code', 'domain', name='payment_purpose_enum'), nullable=False),
    sa.Column('related_id', sa.Uuid(), nullable=True),
    sa.Column('comment', sa.String(length=64), nullable=True),
    sa.Column('destination', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'failed', name='payment_status_enum'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_hash', name='uq_payments_tx_hash')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_comment'), ['comment'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_tx_hash'), ['tx_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_user_id'), ['user_id'], unique=False)

    op.create_table('sites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('visitka', 'links', 'landing', 'portfolio', 'events', 'ton_project', name='site_type_enum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('custom_code', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('custom_code_paid', sa.Boolean(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('tld', sa.String(length=32), nullable=True),
    sa.Column('dns_item_address', sa.String(length=128), nullable=True),
    sa.Column('collection_address', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('draft', 'publishing', 'published', 'publish_error', 'expired', name='site_status_enum'), nullable=False),
    sa.Column('storage_bag_id', sa.String(length=128), nullable=True),
    sa.Column('publish_error', sa.Text(), nullable=True),
    sa.Column('publish_job_id', sa.String(length=64), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sites_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_sites_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_sites_user_status', ['user_id', 'status'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tariff_id', sa.Uuid(), nullable=True),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_forever', sa.Boolean(), nullable=False),
    sa.Column('is_trial', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('active', 'expiring_soon', 'expired', 'manual', name='subscription_status_enum'), nullable=False),
    sa.Column('granted_by_admin', sa.Boolean(), nullable=False),
    sa.Column('notified_expiring', sa.Boolean(), nullable=False),
    sa.Column('notified_expired', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariffs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_tariff_id'), ['tariff_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_tariff_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_site_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_expires_at'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_index('ix_sites_user_status')
        batch_op.drop_index(batch_op.f('ix_sites_user_id'))
        batch_op.drop_index(batch_op.f('ix_sites_domain'))

    op.drop_table('sites')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_user_id'))
        batch_op.drop_index(batch_op.f('ix_payments_tx_hash'))
        batch_op.drop_index(batch_op.f('ix_payments_comment'))

    op.drop_table('payments')
    with op.batch_alter_table('admin_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_actions_target_user_id'))
        batch_op.drop_index(batch_op.f('ix_admin_actions_admin_id'))

    op.drop_table('admin_actions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_wallet_address'))
        batch_op.drop_index(batch_op.f('ix_users_telegram_id'))

    op.drop_table('users')
    with op.batch_alter_table('ton_proof_payloads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ton_proof_payloads_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_ton_proof_payloads_payload'))

    op.drop_table('ton_proof_payloads')
    op.drop_table('tariffs')
    # ### end Alembic commands ###
